### ISSUE TITLE
Use androidautoversion for versioning

### ISSUE THREAD

**Issue by alexfu** [ChrisGuzman/BrowserInterceptor#3]
Not really an issue as opposed to a shameless suggestion: https://github.com/alexfu/androidautoversion. Would love to get your feedback on it and see what you think.

**Comment by TheChrisVela** [comment]
Oh I just saw this! Will check it out for the next release.

**Comment by TheChrisVela** [comment]
Added it in develop: https://github.com/ChrisGuzman/BrowserInterceptor/pull/4/commits/e4f27338b104eda8b7171f02056b9bebb88b7c79

Thanks again! Looking forward to using this for the next deploy
